Repository Vineflower/vineflower, pull requests merged in 2022-08, with the labels that each got.

#188 Improve noargs message and add a help argument + detailed message
  src/org/jetbrains/java/decompiler/main/decompiler/ConsoleDecompiler.java
  src/org/jetbrains/java/decompiler/main/decompiler/ConsoleHelp.java
Labels: Priority: High, Subsystem: User-Facing

#187 Add Scala tests
  .gitignore
  build.gradle
  test/org/jetbrains/java/decompiler/DecompilerTestFixture.java
  test/org/jetbrains/java/decompiler/SingleClassesTest.java
  test/org/jetbrains/java/decompiler/SingleClassesTestBase.java
  testData/results/pkg/TestCaseClasses.dec
  testData/results/pkg/TestCompanionObject.dec
  testData/results/pkg/TestObject.dec
  testData/src/scala/pkg/TestCaseClasses.scala
  testData/src/scala/pkg/TestCompanionObject.scala
  testData/src/scala/pkg/TestObject.scala
Labels: Priority: Medium, unit test

#197 fix: Correct improper class paths from dir source
  src/org/jetbrains/java/decompiler/struct/DirectoryContextSource.java
Labels: Priority: High, Subsystem: User-Facing, bugfix
