Repository Vineflower/vineflower, pull requests merged in 2022-05, with the labels that each got.

#103 Provide new api to handle StatEdges
  src/org/jetbrains/java/decompiler/modules/decompiler/IdeaNotNullHelper.java
  src/org/jetbrains/java/decompiler/modules/decompiler/StatEdge.java
  src/org/jetbrains/java/decompiler/modules/decompiler/stats/Statement.java
Labels: Subsystem: Statement Structure, Priority: Medium, code quality

#106 Fix statement graph validation
  src/org/jetbrains/java/decompiler/modules/decompiler/EliminateLoopsHelper.java
  src/org/jetbrains/java/decompiler/modules/decompiler/IfHelper.java
  src/org/jetbrains/java/decompiler/modules/decompiler/LabelHelper.java
  src/org/jetbrains/java/decompiler/modules/decompiler/MergeHelper.java
  src/org/jetbrains/java/decompiler/modules/decompiler/StatEdge.java
  src/org/jetbrains/java/decompiler/modules/decompiler/SwitchExpressionHelper.java
  src/org/jetbrains/java/decompiler/modules/decompiler/ValidationHelper.java
  src/org/jetbrains/java/decompiler/modules/decompiler/stats/Statement.java
Labels: Subsystem: Statement Structure, Priority: Medium, code quality

#104 Refactor/ifhelper improvements and ternary support
  src/org/jetbrains/java/decompiler/main/rels/MethodProcessorRunnable.java
  src/org/jetbrains/java/decompiler/modules/decompiler/IfHelper.java
  src/org/jetbrains/java/decompiler/modules/decompiler/IfNode.java
  src/org/jetbrains/java/decompiler/modules/decompiler/MergeHelper.java
  src/org/jetbrains/java/decompiler/modules/decompiler/TernaryProcessor.java
  src/org/jetbrains/java/decompiler/modules/decompiler/ValidationHelper.java
  testData/results/pkg/TestIfTernary2.dec
  testData/results/pkg/TestIfTernaryReturn.dec
  testData/results/pkg/TestNestedTernaryAssign.dec
  testData/results/pkg/TestNestedTernaryCondition.dec
  testData/results/pkg/TestTernaryCall.dec
  testData/results/pkg/TestTernaryReturn.dec
  testData/results/pkg/TestWhileConditionTernary.dec
  testData/results/pkg/TestWhileTernary6.dec
  testData/results/pkg/TestWhileTernary8.dec
  testData/results/pkg/TestWhileTernary9.dec
Labels: Subsystem: Statement Structure, Priority: High, code quality

#93 Do not allow the `IfPatternMatchProcessor` to override an earlier match
  src/org/jetbrains/java/decompiler/modules/decompiler/IfPatternMatchProcessor.java
  testData/results/pkg/TestPatternMatching17FakeNew.dec
  testData/results/pkg/TestPatternMatchingFakeNew.dec
Labels: enhancement, Subsystem: Statement Structure, Priority: Medium, Subsystem: Variables

#109 Remove the mapPredStates and mapSuccStates
  src/org/jetbrains/java/decompiler/modules/decompiler/StatEdge.java
  src/org/jetbrains/java/decompiler/modules/decompiler/stats/Statement.java
Labels: Subsystem: Statement Structure, Priority: Medium, code quality

#108 Fix inacessible digraph nodes
  src/org/jetbrains/java/decompiler/main/rels/MethodProcessorRunnable.java
  src/org/jetbrains/java/decompiler/modules/decompiler/ExitHelper.java
  src/org/jetbrains/java/decompiler/modules/decompiler/ValidationHelper.java
  src/org/jetbrains/java/decompiler/modules/decompiler/sforms/FlattenStatementsHelper.java
  src/org/jetbrains/java/decompiler/util/DotExporter.java
  test/org/jetbrains/java/decompiler/SingleClassesTest.java
  testData/results/pkg/TestClassLoop.dec
  testData/results/pkg/TestLoopFinally.dec
  testData/src/java8/pkg/TestClassLoop.java
  testData/src/java8/pkg/TestLoopFinally.java
Labels: Subsystem: Statement Structure, Priority: Medium

#110 Improve dot files
  src/org/jetbrains/java/decompiler/util/DotExporter.java
Labels: enhancement, Priority: Medium

#113 Fix incorrect assignment exprent modification, for assignments with a condition (eg XOR)
  src/org/jetbrains/java/decompiler/modules/decompiler/SecondaryFunctionsHelper.java
Labels: bug, Priority: High, Subsystem: Variables

#114 feat: SourceFile debug comments
  src/org/jetbrains/java/decompiler/main/ClassWriter.java
  src/org/jetbrains/java/decompiler/main/extern/IFernflowerPreferences.java
  src/org/jetbrains/java/decompiler/struct/attr/StructGeneralAttribute.java
  src/org/jetbrains/java/decompiler/struct/attr/StructSourceFileAttribute.java
Labels: enhancement, Priority: Medium, Subsystem: Parsing

#124 build: Bump Kotlin version to 1.6.21
  build.gradle
  testData/results/pkg/TestIllegalVarName.dec
  testData/results/pkg/TestKotlinConstructorKt.dec
  testData/results/pkg/TestKotlinEnumWhen.dec
  testData/results/pkg/TestNamedSuspendFun2Kt.dec
  testData/results/pkg/TestRunSuspend.dec
  testData/results/pkg/TestSuspendLambdaKt.dec
  testData/results/pkg/TestSynchronizedUnprotected.dec
Labels: enhancement, Priority: High, unit test

#119 fix: README arguments list
  README.md
  src/org/jetbrains/java/decompiler/main/extern/IFernflowerPreferences.java
Labels: enhancement, Priority: Medium, Subsystem: User-Facing

#116 Make sure that block inlining doesn't cause validation to fail
  src/org/jetbrains/java/decompiler/modules/decompiler/InlineSingleBlockHelper.java
  src/org/jetbrains/java/decompiler/modules/decompiler/MergeHelper.java
  src/org/jetbrains/java/decompiler/modules/decompiler/ValidationHelper.java
  src/org/jetbrains/java/decompiler/modules/decompiler/stats/Statement.java
  src/org/jetbrains/java/decompiler/util/DotExporter.java
  testData/results/pkg/TestClassSwitch.dec
  testData/results/pkg/TestSwitchLoop.dec
  testData/src/java8/pkg/TestClassSwitch.java
  testData/src/java8/pkg/TestSwitchLoop.java
Labels: Subsystem: Statement Structure, Priority: Medium, bugfix

#107 Refactor/ssa and ssau improvements
  src/org/jetbrains/java/decompiler/modules/decompiler/sforms/SSAConstructorSparseEx.java
  src/org/jetbrains/java/decompiler/modules/decompiler/sforms/SSAUConstructorSparseEx.java
  src/org/jetbrains/java/decompiler/modules/decompiler/sforms/VarMapHolder.java
  src/org/jetbrains/java/decompiler/util/DotExporter.java
  test/org/jetbrains/java/decompiler/SingleClassesTest.java
  testData/results/pkg/TestDefiniteAssignment.dec
  testData/src/java17/pkg/TestDefiniteAssignment.java
Labels: Subsystem: Statement Structure, Priority: Medium, code quality

#95 ssa and ssau merge
  src/org/jetbrains/java/decompiler/modules/decompiler/sforms/SFormsConstructor.java
  src/org/jetbrains/java/decompiler/modules/decompiler/sforms/SSAConstructorSparseEx.java
  src/org/jetbrains/java/decompiler/modules/decompiler/sforms/SSAUConstructorSparseEx.java
  src/org/jetbrains/java/decompiler/modules/decompiler/vars/VarVersionEdge.java
  src/org/jetbrains/java/decompiler/modules/decompiler/vars/VarVersionsProcessor.java
Labels: Subsystem: Statement Structure, Priority: High, Subsystem: Variables, code quality

#129 (Exhaustive) switch improvements
  src/org/jetbrains/java/decompiler/modules/decompiler/SwitchHelper.java
  src/org/jetbrains/java/decompiler/modules/decompiler/exps/SwitchExprent.java
  test/org/jetbrains/java/decompiler/DecompilerTestFixture.java
  test/org/jetbrains/java/decompiler/SingleClassesTest.java
  testData/results/pkg/TestInlineSwitchExpression1.dec
  testData/results/pkg/TestInlineSwitchExpression3.dec
  testData/results/pkg/TestSwitchPatternMatching6.dec
  testData/results/pkg/TestSwitchPatternMatching7.dec
  testData/results/pkg/TestSwitchPatternMatching8.dec
  testData/results/pkg/TestSwitchPatternMatching9.dec
  testData/src/java17preview/ext/Direction.java
  testData/src/java17preview/pkg/TestSwitchPatternMatching6.java
  testData/src/java17preview/pkg/TestSwitchPatternMatching7.java
  testData/src/java17preview/pkg/TestSwitchPatternMatching8.java
  testData/src/java17preview/pkg/TestSwitchPatternMatching9.java
Labels: enhancement, Subsystem: Statement Structure, Priority: Medium

#145 Add support for static and transitive modifiers of 'requires' in module-info
  src/org/jetbrains/java/decompiler/code/CodeConstants.java
  src/org/jetbrains/java/decompiler/main/ClassWriter.java
  testData/results/module-info.dec
  testData/src/java9/sample.module/module-info.java
Labels: enhancement, Subsystem: Writing, Priority: Medium

#146 Switch fixes
  src/org/jetbrains/java/decompiler/modules/decompiler/SwitchHelper.java
  src/org/jetbrains/java/decompiler/modules/decompiler/SwitchPatternMatchProcessor.java
  src/org/jetbrains/java/decompiler/modules/decompiler/exps/SwitchExprent.java
  src/org/jetbrains/java/decompiler/modules/decompiler/stats/SwitchStatement.java
  test/org/jetbrains/java/decompiler/SingleClassesTest.java
  testData/results/pkg/TestSwitchPatternMatching1.dec
  testData/results/pkg/TestSwitchPatternMatching10.dec
  testData/results/pkg/TestSwitchPatternMatching11.dec
  testData/results/pkg/TestSwitchPatternMatching12.dec
  testData/results/pkg/TestSwitchPatternMatching3.dec
  testData/results/pkg/TestSwitchPatternMatching4.dec
  testData/results/pkg/TestSwitchPatternMatching6.dec
  testData/results/pkg/TestSwitchPatternMatching7.dec
  testData/results/pkg/TestSwitchPatternMatchingConstructor2.dec
  testData/results/pkg/TestSwitchPatternMatchingReturn1.dec
  testData/src/java17preview/pkg/TestSwitchPatternMatching10.java
  testData/src/java17preview/pkg/TestSwitchPatternMatching11.java
  testData/src/java17preview/pkg/TestSwitchPatternMatching12.java
Labels: enhancement, Subsystem: Statement Structure, Priority: Medium

#148 Don't run processing steps on statements the method doesn't have
  src/org/jetbrains/java/decompiler/main/rels/MethodProcessorRunnable.java
  src/org/jetbrains/java/decompiler/modules/decompiler/stats/RootStatement.java
Labels: enhancement, Subsystem: Statement Structure, Priority: Low, code quality

#153 Resolves #151: Remove Unnecessary String.valueOfs()
  src/org/jetbrains/java/decompiler/modules/decompiler/ConcatenationHelper.java
  test/org/jetbrains/java/decompiler/SingleClassesTest.java
  testData/classes/custom/TestStringConcatJ19.class
  testData/results/TestStringConcatJ19.dec
Labels: enhancement, Subsystem: Statement Structure, Priority: Medium

#156 Add FlattenStatementsHelper support for switch cases
  src/org/jetbrains/java/decompiler/main/rels/ClassWrapper.java
  src/org/jetbrains/java/decompiler/modules/decompiler/flow/DirectEdge.java
  src/org/jetbrains/java/decompiler/modules/decompiler/flow/DirectNodeType.java
  src/org/jetbrains/java/decompiler/modules/decompiler/flow/FlattenStatementsHelper.java
  src/org/jetbrains/java/decompiler/modules/decompiler/stats/Statement.java
  src/org/jetbrains/java/decompiler/modules/decompiler/stats/SwitchStatement.java
Labels: enhancement, Subsystem: Statement Structure, Priority: High

#138 Make catch blocks aware of all assignments in the try blocks
  src/org/jetbrains/java/decompiler/modules/decompiler/flow/DirectNode.java
  src/org/jetbrains/java/decompiler/modules/decompiler/flow/FlattenStatementsHelper.java
  src/org/jetbrains/java/decompiler/modules/decompiler/sforms/SFormsConstructor.java
  src/org/jetbrains/java/decompiler/modules/decompiler/sforms/VarMapHolder.java
  src/org/jetbrains/java/decompiler/util/SFormsFastMapDirect.java
  testData/results/pkg/TestSynchronizedTrySharing.dec
  testData/results/pkg/TestTryReturn.dec
  testData/results/pkg/TestTryReturnNoDebug.dec
  testData/results/pkg/TestTrySynchronized.dec
  testData/results/pkg/TestTryVar.dec
  testData/results/pkg/TestTryVarNoDebug.dec
Labels: enhancement, Priority: High, Subsystem: Variables

#134 DirectNode refactoring to use edges, move to flow package
  src/org/jetbrains/java/decompiler/main/ClassReference14Processor.java
  src/org/jetbrains/java/decompiler/main/rels/ClassWrapper.java
  src/org/jetbrains/java/decompiler/main/rels/MethodProcessorRunnable.java
  src/org/jetbrains/java/decompiler/main/rels/MethodWrapper.java
  src/org/jetbrains/java/decompiler/main/rels/NestedClassProcessor.java
  src/org/jetbrains/java/decompiler/main/rels/NestedMemberAccess.java
  src/org/jetbrains/java/decompiler/modules/decompiler/ExprProcessor.java
  src/org/jetbrains/java/decompiler/modules/decompiler/FinallyProcessor.java
  src/org/jetbrains/java/decompiler/modules/decompiler/MergeHelper.java
  src/org/jetbrains/java/decompiler/modules/decompiler/PPandMMHelper.java
  src/org/jetbrains/java/decompiler/modules/decompiler/StackVarsProcessor.java
  src/org/jetbrains/java/decompiler/modules/decompiler/ValidationHelper.java
  src/org/jetbrains/java/decompiler/modules/decompiler/flow/DirectEdge.java
  src/org/jetbrains/java/decompiler/modules/decompiler/flow/DirectEdgeType.java
  src/org/jetbrains/java/decompiler/modules/decompiler/flow/DirectGraph.java
  src/org/jetbrains/java/decompiler/modules/decompiler/flow/DirectNode.java
  src/org/jetbrains/java/decompiler/modules/decompiler/flow/DirectNodeType.java
  src/org/jetbrains/java/decompiler/modules/decompiler/flow/FlattenStatementsHelper.java
  src/org/jetbrains/java/decompiler/modules/decompiler/sforms/DirectNode.java
  src/org/jetbrains/java/decompiler/modules/decompiler/sforms/SFormsConstructor.java
  src/org/jetbrains/java/decompiler/modules/decompiler/sforms/VarMapHolder.java
  src/org/jetbrains/java/decompiler/modules/decompiler/stats/Statement.java
  src/org/jetbrains/java/decompiler/modules/decompiler/stats/SwitchStatement.java
  src/org/jetbrains/java/decompiler/modules/decompiler/vars/VarTypeProcessor.java
  src/org/jetbrains/java/decompiler/modules/decompiler/vars/VarVersionsProcessor.java
  src/org/jetbrains/java/decompiler/util/DotExporter.java
  src/org/jetbrains/java/decompiler/util/SFormsFastMapDirect.java
  src/org/jetbrains/java/decompiler/util/StatementIterator.java
  testData/results/pkg/TestSynchronizedTrySharing.dec
  testData/results/pkg/TestTryReturn.dec
  testData/results/pkg/TestTryReturnNoDebug.dec
  testData/results/pkg/TestTrySynchronized.dec
  testData/results/pkg/TestTryVar.dec
  testData/results/pkg/TestTryVarNoDebug.dec
Labels: enhancement, Subsystem: Statement Structure, Priority: High, code quality

#135 Handle JDK constant dynamic bootstraps
  README.md
  src/org/jetbrains/java/decompiler/main/extern/IFernflowerPreferences.java
  src/org/jetbrains/java/decompiler/modules/decompiler/CondyHelper.java
  src/org/jetbrains/java/decompiler/modules/decompiler/ExprProcessor.java
  src/org/jetbrains/java/decompiler/modules/decompiler/exps/ConstExprent.java
  src/org/jetbrains/java/decompiler/modules/decompiler/exps/FieldExprent.java
  src/org/jetbrains/java/decompiler/modules/decompiler/exps/InvocationExprent.java
  test/org/jetbrains/java/decompiler/SingleClassesTest.java
  testData/results/pkg/TestComplexCondy.dec
  testData/results/pkg/TestCondy.dec
  testData/src/jasm/TestComplexCondy.jasm
  testData/src/jasm/TestCondy.jasm
Labels: enhancement, Subsystem: Statement Structure, Priority: Medium
