Repository Vineflower/vineflower, pull requests merged in 2022-04, with the labels that each got.

#90 Add test for ternaries inside while conditions
  test/org/jetbrains/java/decompiler/SingleClassesTest.java
  testData/results/pkg/TestWhileConditionTernary.dec
  testData/src/java8/pkg/TestWhileConditionTernary.java
Labels: Subsystem: Statement Structure, Priority: High, unit test

#84 Adjust IResultSaver to support both Fabricflower and Forgeflower APIs
  build.gradle
  src/net/fabricmc/fernflower/api/IFabricResultSaver.java
  src/org/jetbrains/java/decompiler/main/decompiler/ConsoleDecompiler.java
  src/org/jetbrains/java/decompiler/main/extern/IResultSaver.java
  src/org/jetbrains/java/decompiler/struct/ContextUnit.java
Labels: enhancement, Priority: High

#94 Port dump code lines option from ForgeFlower
  src/org/jetbrains/java/decompiler/main/decompiler/ConsoleDecompiler.java
  src/org/jetbrains/java/decompiler/main/decompiler/SingleFileSaver.java
  src/org/jetbrains/java/decompiler/main/extern/IFernflowerPreferences.java
  src/org/jetbrains/java/decompiler/main/extern/IResultSaver.java
Labels: enhancement, Subsystem: IO, Priority: High

#96 Merge 1.8.1
  build.gradle
  src/org/jetbrains/java/decompiler/main/decompiler/ConsoleDecompiler.java
  src/org/jetbrains/java/decompiler/main/decompiler/DirectoryResultSaver.java
  src/org/jetbrains/java/decompiler/main/decompiler/SingleFileSaver.java
  src/org/jetbrains/java/decompiler/main/extern/IFernflowerPreferences.java
  src/org/jetbrains/java/decompiler/main/extern/IResultSaver.java
  src/org/jetbrains/java/decompiler/struct/ContextUnit.java
Labels: Priority: High, Version Update
