Repository Vineflower/vineflower, pull requests merged in 2022-07, with the labels that each got.

#180 Test duplicate assignment in switch expression
  test/org/jetbrains/java/decompiler/SingleClassesTest.java
  testData/results/pkg/TestDuplicateAssignmentInSwitchExpr.dec
  testData/src/java17/pkg/TestDuplicateAssignmentInSwitchExpr.java
Labels: unit test

#179 Added Implementation-Version to manifest
  build.gradle
Labels: enhancement

#154 Fix loops from extending too far due to postdominance not discovering all possible nodes
  src/org/jetbrains/java/decompiler/main/rels/MethodProcessorRunnable.java
  src/org/jetbrains/java/decompiler/modules/decompiler/decompose/DomHelper.java
  src/org/jetbrains/java/decompiler/modules/decompiler/decompose/DominatorEngine.java
  src/org/jetbrains/java/decompiler/modules/decompiler/decompose/FastExtendedPostdominanceHelper.java
  src/org/jetbrains/java/decompiler/modules/decompiler/decompose/StrongConnectivityHelper.java
  src/org/jetbrains/java/decompiler/modules/decompiler/decompose/SupportComponent.java
  src/org/jetbrains/java/decompiler/modules/decompiler/stats/Statement.java
  src/org/jetbrains/java/decompiler/util/FastFixedSetFactory.java
  src/org/jetbrains/java/decompiler/util/VBStyleCollection.java
  test/org/jetbrains/java/decompiler/StronglyConnectedComponentsTest.java
  testData/results/pkg/TestForeachMultipleLoops.dec
  testData/src/java8/pkg/TestForeachMultipleLoops.java
Labels: enhancement, Subsystem: Statement Structure, Priority: Medium

#45 Refactor: Reduce `BasicBlock` id accesses
  src/org/jetbrains/java/decompiler/code/cfg/BasicBlock.java
  src/org/jetbrains/java/decompiler/code/cfg/ExceptionRangeCFG.java
  src/org/jetbrains/java/decompiler/modules/decompiler/FinallyProcessor.java
  src/org/jetbrains/java/decompiler/util/DotExporter.java
  testData/results/pkg/TestTryReturn.dec
Labels: enhancement, Priority: Low

#184 Use SSAU to validate finally blocks with variables inside
  src/org/jetbrains/java/decompiler/main/rels/MethodProcessorRunnable.java
  src/org/jetbrains/java/decompiler/modules/decompiler/ExprProcessor.java
  src/org/jetbrains/java/decompiler/modules/decompiler/FinallyProcessor.java
  src/org/jetbrains/java/decompiler/modules/decompiler/StackVarsProcessor.java
  src/org/jetbrains/java/decompiler/modules/decompiler/exps/AssignmentExprent.java
  src/org/jetbrains/java/decompiler/modules/decompiler/exps/VarExprent.java
  src/org/jetbrains/java/decompiler/modules/decompiler/sforms/SimpleSSAReassign.java
  src/org/jetbrains/java/decompiler/modules/decompiler/vars/VarProcessor.java
  src/org/jetbrains/java/decompiler/modules/decompiler/vars/VarVersionsGraph.java
  src/org/jetbrains/java/decompiler/util/DotExporter.java
  test/org/jetbrains/java/decompiler/SingleClassesTest.java
  testData/results/pkg/TestFinallyBlockVariableUse.dec
  testData/results/pkg/TestLoopFinally.dec
  testData/results/pkg/TestTryFinally.dec
  testData/results/pkg/TestTryReturn.dec
Labels: enhancement, Subsystem: Statement Structure, Priority: High

#120 Introduce real lazy loading for the decompile classpath
  README.md
  build.gradle
  java9/org/jetbrains/java/decompiler/util/ClasspathScanner.java
  src/org/jetbrains/java/decompiler/code/CodeConstants.java
  src/org/jetbrains/java/decompiler/main/ClassesProcessor.java
  src/org/jetbrains/java/decompiler/main/Fernflower.java
  src/org/jetbrains/java/decompiler/main/decompiler/BaseDecompiler.java
  src/org/jetbrains/java/decompiler/main/decompiler/ConsoleDecompiler.java
  src/org/jetbrains/java/decompiler/main/decompiler/ConsoleFileSaver.java
  src/org/jetbrains/java/decompiler/main/decompiler/SingleFileSaver.java
  src/org/jetbrains/java/decompiler/main/extern/IBytecodeProvider.java
  src/org/jetbrains/java/decompiler/main/extern/IContextSource.java
  src/org/jetbrains/java/decompiler/main/extern/IFernflowerPreferences.java
  src/org/jetbrains/java/decompiler/main/extern/IResultSaver.java
  src/org/jetbrains/java/decompiler/modules/renamer/IdentifierConverter.java
  src/org/jetbrains/java/decompiler/struct/ContextUnit.java
  src/org/jetbrains/java/decompiler/struct/DirectoryContextSource.java
  src/org/jetbrains/java/decompiler/struct/JarContextSource.java
  src/org/jetbrains/java/decompiler/struct/SingleFileContextSource.java
  src/org/jetbrains/java/decompiler/struct/StructClass.java
  src/org/jetbrains/java/decompiler/struct/StructContext.java
  src/org/jetbrains/java/decompiler/struct/attr/StructModuleAttribute.java
  src/org/jetbrains/java/decompiler/struct/lazy/LazyLoader.java
  src/org/jetbrains/java/decompiler/util/ClasspathScanner.java
  src/org/jetbrains/java/decompiler/util/InterpreterUtil.java
  src/org/jetbrains/java/decompiler/util/JrtFinder.java
  src/org/jetbrains/java/decompiler/util/ModuleBasedContextSource.java
  test/org/jetbrains/java/decompiler/DecompilerTestFixture.java
  test/org/jetbrains/java/decompiler/SingleClassesTestBase.java
  testData/results/pkg/TestIllegalVarName.dec
  testData/results/pkg/TestRenameEntities.dec
Labels: enhancement, Priority: High, Subsystem: Parsing, Subsystem: User-Facing
