Repository Vineflower/vineflower, pull requests merged in 2023-07, with the labels that each got.

#252 Ensure deterministic artifact JARs
  build.gradle
Labels: enhancement, Priority: High

#283 fix: prepare for publishing exclusively to Central
  .github/workflows/release.yml
  .github/workflows/snapshot.yml
  build.gradle
Labels: Priority: High, infra

#291 Fix local variable jad name and type where the debug name conflicts
  src/org/jetbrains/java/decompiler/main/rels/NestedClassProcessor.java
Labels: enhancement, Priority: High, Subsystem: Variables
