Repository Vineflower/vineflower, pull requests merged in 2023-09, with the labels that each got.

#305 Release 1.9.3
  README.md
  build.gradle
  src/org/jetbrains/java/decompiler/main/ClassWriter.java
  src/org/jetbrains/java/decompiler/main/ClassesProcessor.java
  src/org/jetbrains/java/decompiler/main/DecompilerContext.java
  src/org/jetbrains/java/decompiler/main/Fernflower.java
  src/org/jetbrains/java/decompiler/main/decompiler/PrintStreamLogger.java
  src/org/jetbrains/java/decompiler/main/extern/IFernflowerLogger.java
  src/org/jetbrains/java/decompiler/modules/decompiler/exps/ConstExprent.java
  src/org/jetbrains/java/decompiler/struct/ContextUnit.java
  src/org/jetbrains/java/decompiler/struct/IDecompiledData.java
  test/org/jetbrains/java/decompiler/SingleClassesTest.java
  testData/results/pkg/TestInnerClassExtend.dec
  testData/results/pkg/TestInnerClassReference.dec
  testData/src/java8/ext/SomeOuterClass.java
  testData/src/java8/pkg/TestInnerClassExtend.java
  testData/src/java8/pkg/TestInnerClassReference.java
Labels: Priority: High, Version Update

#275 Kotlin property decompilation
  plugins/kotlin/src/main/java/org/vineflower/kotlin/KotlinChooser.java
  plugins/kotlin/src/main/java/org/vineflower/kotlin/KotlinDecompilationContext.java
  plugins/kotlin/src/main/java/org/vineflower/kotlin/KotlinPreferences.java
  plugins/kotlin/src/main/java/org/vineflower/kotlin/KotlinWriter.java
  plugins/kotlin/src/main/java/org/vineflower/kotlin/struct/KProperty.java
  plugins/kotlin/src/main/java/org/vineflower/kotlin/struct/KPropertyAccessor.java
  plugins/kotlin/src/main/java/org/vineflower/kotlin/struct/KType.java
  plugins/kotlin/src/main/java/org/vineflower/kotlin/util/KTypes.java
  plugins/kotlin/testData/results/pkg/TestClassDec.dec
  plugins/kotlin/testData/results/pkg/TestCompileTimeErrors.dec
  plugins/kotlin/testData/results/pkg/TestConvertedK2JOps.dec
  plugins/kotlin/testData/results/pkg/TestDataClass.dec
  plugins/kotlin/testData/results/pkg/TestKotlinTypes.dec
  plugins/kotlin/testData/results/pkg/TestNonInlineLambda.dec
  plugins/kotlin/testData/results/pkg/TestObject.dec
  plugins/kotlin/testData/results/pkg/TestPoorNames.dec
  plugins/kotlin/testData/results/pkg/TestSealedHierarchy.dec
  plugins/kotlin/testData/results/pkg/TestTopLevelKt.dec
Labels: enhancement, Subsystem: Writing, Priority: Medium

#282 A bunch of changes mostly related to ssau
  plugins/kotlin/src/main/java/org/vineflower/kotlin/pass/EliminateDeadVarsPass.java
  src/org/jetbrains/java/decompiler/main/rels/MethodProcessor.java
  src/org/jetbrains/java/decompiler/modules/decompiler/FinallyProcessor.java
  src/org/jetbrains/java/decompiler/modules/decompiler/SecondaryFunctionsHelper.java
  src/org/jetbrains/java/decompiler/modules/decompiler/SimplifyExprentsHelper.java
  src/org/jetbrains/java/decompiler/modules/decompiler/StackVarsProcessor.java
  src/org/jetbrains/java/decompiler/modules/decompiler/ValidationHelper.java
  src/org/jetbrains/java/decompiler/modules/decompiler/decompose/GenericDominatorEngine.java
  src/org/jetbrains/java/decompiler/modules/decompiler/exps/AssignmentExprent.java
  src/org/jetbrains/java/decompiler/modules/decompiler/exps/Exprent.java
  src/org/jetbrains/java/decompiler/modules/decompiler/exps/FieldExprent.java
  src/org/jetbrains/java/decompiler/modules/decompiler/exps/FunctionExprent.java
  src/org/jetbrains/java/decompiler/modules/decompiler/exps/IfExprent.java
  src/org/jetbrains/java/decompiler/modules/decompiler/exps/InvocationExprent.java
  src/org/jetbrains/java/decompiler/modules/decompiler/exps/NewExprent.java
  src/org/jetbrains/java/decompiler/modules/decompiler/exps/VarExprent.java
  src/org/jetbrains/java/decompiler/modules/decompiler/sforms/SFormsConstructor.java
  src/org/jetbrains/java/decompiler/modules/decompiler/sforms/SSAConstructorSparseEx.java
  src/org/jetbrains/java/decompiler/modules/decompiler/sforms/SSAUConstructorSparseEx.java
  src/org/jetbrains/java/decompiler/modules/decompiler/sforms/SimpleSSAReassign.java
  src/org/jetbrains/java/decompiler/modules/decompiler/sforms/VarMapHolder.java
  src/org/jetbrains/java/decompiler/modules/decompiler/vars/VarVersionEdge.java
  src/org/jetbrains/java/decompiler/modules/decompiler/vars/VarVersionNode.java
  src/org/jetbrains/java/decompiler/modules/decompiler/vars/VarVersionsGraph.java
  src/org/jetbrains/java/decompiler/modules/decompiler/vars/VarVersionsProcessor.java
  src/org/jetbrains/java/decompiler/util/DotExporter.java
  src/org/jetbrains/java/decompiler/util/collections/SFormsFastMapDirect.java
  test/org/jetbrains/java/decompiler/SingleClassesTest.java
  testData/results/pkg/TestArrayAssign.dec
  testData/results/pkg/TestArrayFieldAccess2.dec
  testData/results/pkg/TestAssignmentTernaryConstantSimplification.dec
  testData/results/pkg/TestDoWhileMerge.dec
  testData/results/pkg/TestDoublePopAfterJump.dec
  testData/results/pkg/TestLoopReturn.dec
  testData/results/pkg/TestNextGaussian.dec
  testData/results/pkg/TestObjectArrays.dec
  testData/results/pkg/TestPPMMPhi.dec
  testData/results/pkg/TestPatternMatching17FakeLoops.dec
  testData/results/pkg/TestPatternMatching17FakeLoopsInverted.dec
  testData/results/pkg/TestPatternMatching17FakeNew.dec
  testData/results/pkg/TestPatternMatchingCompoundBool.dec
  testData/results/pkg/TestPatternMatchingFakeLoops.dec
  testData/results/pkg/TestPatternMatchingFakeLoopsInverted.dec
  testData/results/pkg/TestPatternMatchingFakeNew.dec
  testData/results/pkg/TestReturnTernaryConstantSimplification.dec
  testData/results/pkg/TestSwitchPatternMatching15.dec
  testData/results/pkg/TestSwitchPatternMatching21.dec
  testData/results/pkg/TestSwitchPatternMatchingInstanceof1.dec
  testData/results/pkg/TestSwitchPatternMatchingInstanceof2.dec
  testData/results/pkg/TestWhileForeach.dec
  testData/src/java8/pkg/TestArrayAssign.java
  testData/src/java8/pkg/TestPPMMPhi.java
Labels: enhancement, Subsystem: Statement Structure, Priority: High

#215 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement, Priority: Low

#306 Inline variables when doing pattern matching instanceof
  src/org/jetbrains/java/decompiler/modules/decompiler/IfPatternMatchProcessor.java
  src/org/jetbrains/java/decompiler/modules/decompiler/exps/FunctionExprent.java
  testData/results/pkg/TestIfPatternMatchMethod.dec
  testData/results/pkg/TestRecordPattern2.dec
  testData/results/pkg/TestRecordPattern3.dec
  testData/results/pkg/TestRecordPattern4.dec
  testData/results/pkg/TestSwitchPatternMatchingInstanceof4.dec
Labels: enhancement, Subsystem: Statement Structure, Priority: Medium

#308 Add test for lambda param type loss
  test/org/jetbrains/java/decompiler/SingleClassesTest.java
  testData/results/pkg/TestLambdaParamTypes.dec
  testData/src/java8/pkg/TestLambdaParamTypes.java
Labels: Subsystem: Generics, unit test

#311 Fix final variable definition that is used in a for loop being moved outside the for loop
  src/org/jetbrains/java/decompiler/modules/decompiler/MergeHelper.java
  test/org/jetbrains/java/decompiler/SingleClassesTest.java
  testData/results/pkg/TestWhileLambda.dec
  testData/src/java8/pkg/TestWhileLambda.java
Labels: Priority: Medium, Subsystem: Variables, bugfix

#313 Create some test cases for compile errors in decomp output
  test/org/jetbrains/java/decompiler/SingleClassesTest.java
  testData/results/pkg/TestGenericComparison.dec
  testData/results/pkg/TestLocalRecord.dec
  testData/results/pkg/TestStaticBlockFinalField.dec
  testData/src/java16/pkg/TestLocalRecord.java
  testData/src/java8/pkg/TestGenericComparison.java
  testData/src/java8/pkg/TestStaticBlockFinalField.java
Labels: Priority: Medium, unit test

#320 Make containsKey return true if the key is present and the value is null in NullableConcurrentHashMap
  src/org/jetbrains/java/decompiler/util/collections/NullableConcurrentHashMap.java
  testData/results/pkg/TestGenericsInvocUnchecked.dec
Labels: Subsystem: Generics, Priority: High, bugfix

#321 Allow using generics with pattern matching instanceof
  src/org/jetbrains/java/decompiler/modules/decompiler/IfPatternMatchProcessor.java
  testData/results/pkg/TestSwitchPatternMatchingInstanceof4.dec
Labels: enhancement, Subsystem: Generics, Priority: Medium
