Repository Vineflower/vineflower, pull requests merged in 2024-08, with the labels that each got.

#411 Kotlin 2
  build.gradle
  plugins/kotlin/testData/results/pkg/TestCompileTimeErrors.dec
  plugins/kotlin/testData/results/pkg/TestContracts.dec
  plugins/kotlin/testData/results/pkg/TestConvertedK2JOps.dec
  plugins/kotlin/testData/results/pkg/TestDataClass.dec
  plugins/kotlin/testData/results/pkg/TestDestructors.dec
  plugins/kotlin/testData/results/pkg/TestKotlinTypes.dec
  plugins/kotlin/testData/results/pkg/TestNonInlineLambda.dec
  plugins/kotlin/testData/results/pkg/TestNullableOperator.dec
  plugins/kotlin/testData/results/pkg/TestObject.dec
  plugins/kotlin/testData/results/pkg/TestPoorNames.dec
  plugins/kotlin/testData/results/pkg/TestReflection.dec
  plugins/kotlin/testData/results/pkg/TestSafeCasts.dec
  plugins/kotlin/testData/results/pkg/TestSmartCasts.dec
  plugins/kotlin/testData/results/pkg/TestTailrecFunctions.dec
  plugins/kotlin/testData/results/pkg/TestTopLevelKt.dec
  plugins/kotlin/testData/results/pkg/TestTryCatchExpressions.dec
  plugins/kotlin/testData/results/pkg/TestTryFinallyExpressions.dec
  plugins/kotlin/testData/results/pkg/TestVars.dec
  plugins/kotlin/testData/src/kt/pkg/TestDestructors.kt
  testData/results/pkg/TestIllegalVarName.dec
  testData/results/pkg/TestKotlinConstructorKt.dec
  testData/results/pkg/TestKotlinEnumWhen.dec
  testData/results/pkg/TestNamedSuspendFun2Kt.dec
  testData/results/pkg/TestRunSuspend.dec
  testData/results/pkg/TestSuspendLambdaKt.dec
  testData/results/pkg/TestSynchronizedUnprotected.dec
Labels: Priority: Low, Version Update

#378 Fixes for clashing variable renaming
  src/org/jetbrains/java/decompiler/modules/decompiler/vars/VarDefinitionHelper.java
  test/org/jetbrains/java/decompiler/SingleClassesTest.java
  testData/classes/custom/pkg/TestConflictingLvtNamer$1.class
  testData/classes/custom/pkg/TestConflictingLvtNamer$Position.class
  testData/classes/custom/pkg/TestConflictingLvtNamer.class
  testData/results/pkg/TestConflictingLvtNamer.dec
  testData/results/pkg/TestThrowException.dec
Labels: Priority: Medium, Subsystem: Variables, bugfix

#392 Add option to disable inner classes names validation
  src/org/jetbrains/java/decompiler/main/ClassesProcessor.java
  src/org/jetbrains/java/decompiler/main/extern/IFernflowerPreferences.java
Labels: enhancement, Priority: Medium, Subsystem: Parsing

#415 Remove final from `Statement` subtypes
  src/org/jetbrains/java/decompiler/modules/decompiler/stats/CatchAllStatement.java
  src/org/jetbrains/java/decompiler/modules/decompiler/stats/CatchStatement.java
  src/org/jetbrains/java/decompiler/modules/decompiler/stats/DoStatement.java
  src/org/jetbrains/java/decompiler/modules/decompiler/stats/IfStatement.java
  src/org/jetbrains/java/decompiler/modules/decompiler/stats/SequenceStatement.java
  src/org/jetbrains/java/decompiler/modules/decompiler/stats/SwitchStatement.java
  src/org/jetbrains/java/decompiler/modules/decompiler/stats/SynchronizedStatement.java
Labels: enhancement, Subsystem: Statement Structure, Priority: Low

#417 Adds support for nested record patterns and record patterns in switches
  src/org/jetbrains/java/decompiler/modules/decompiler/IfPatternMatchProcessor.java
  src/org/jetbrains/java/decompiler/modules/decompiler/SwitchPatternMatchProcessor.java
  src/org/jetbrains/java/decompiler/modules/decompiler/exps/SwitchExprent.java
  src/org/jetbrains/java/decompiler/modules/decompiler/stats/SwitchStatement.java
  test/org/jetbrains/java/decompiler/SingleClassesTest.java
  testData/results/pkg/TestRecordPatterns1.dec
  testData/results/pkg/TestRecordPatterns4.dec
  testData/results/pkg/TestRecordPatterns5.dec
  testData/results/pkg/TestRecordPatterns6.dec
  testData/results/pkg/TestRecordPatterns7.dec
  testData/results/pkg/TestUnnamedVar1.dec
  testData/src/java21/pkg/TestRecordPatterns7.java
Labels: enhancement, Subsystem: Statement Structure, Priority: Medium

#418 Decompiler option access API
  plugins/idea-not-null/src/main/java/org/vineflower/ideanotnull/IdeaNotNullOptions.java
  plugins/kotlin/src/main/java/org/vineflower/kotlin/KotlinOptions.java
  plugins/variable-renaming/src/main/java/org/vineflower/variablerenaming/VariableRenamingOptions.java
  src/org/jetbrains/java/decompiler/api/DecompilerOption.java
  src/org/jetbrains/java/decompiler/main/decompiler/ConsoleHelp.java
  src/org/jetbrains/java/decompiler/main/extern/IFernflowerPreferences.java
Labels: enhancement

#423 Fix lambdas in anonymous classes referencing parameters from the root method
  src/org/jetbrains/java/decompiler/modules/decompiler/vars/VarDefinitionHelper.java
  test/org/jetbrains/java/decompiler/SingleClassesTest.java
  testData/results/pkg/TestAnonymousClassToLambda.dec
  testData/src/java8/pkg/TestAnonymousClassToLambda.java
Labels: Priority: High, Subsystem: Variables, bugfix, regression
