Repository Vineflower/vineflower, pull requests merged in 2024-12, with the labels that each got.

#436 Fix requireNonNull call with reusable selectors and fix default being removed from exhaustive switch statements
  src/org/jetbrains/java/decompiler/modules/decompiler/LabelHelper.java
  src/org/jetbrains/java/decompiler/modules/decompiler/SwitchPatternMatchProcessor.java
  testData/results/pkg/TestSwitchPatternMatching15.dec
  testData/results/pkg/TestSwitchPatternMatchingJ21.dec
  testData/src/java21/pkg/TestSwitchPatternMatchingJ21.java
Labels: Type: Enhancement, Subsystem: Statement Structure, Priority: High

#437 Add test for labeled blocks in constructor
  test/org/jetbrains/java/decompiler/SingleClassesTest.java
  testData/results/pkg/TestLabeledBlockInConstructor.dec
  testData/src/java8/pkg/TestLabeledBlockInConstructor.java
Labels: Priority: Medium, Type: Unit Tests

#444 Properly walk the inheritance tree when checking for possibly ambiguous unboxed calls
  src/org/jetbrains/java/decompiler/modules/decompiler/exps/InvocationExprent.java
  test/org/jetbrains/java/decompiler/SingleClassesTest.java
  testData/results/pkg/TestBoxingSuperclass.dec
  testData/src/java8/pkg/TestBoxingSuperclass.java
Labels: Subsystem: Writing, Priority: Medium, bugfix
