Repository Vineflower/vineflower, pull requests merged in 2024-01, with the labels that each got.

#334 Renaming plugin
  build.gradle
  buildSrc/build.gradle
  buildSrc/src/main/groovy/org/vineflower/build/TestDataRuntimesProvider.groovy
  buildSrc/src/main/java/org/vineflower/build/JasmCompile.java
  buildSrc/src/main/java/org/vineflower/build/JasmCompileOptions.java
  plugins/variable-renaming/.gitignore
  plugins/variable-renaming/build.gradle
  plugins/variable-renaming/gradle.properties
  plugins/variable-renaming/src/main/java/org/vineflower/variablerenaming/JADNameProvider.java
  plugins/variable-renaming/src/main/java/org/vineflower/variablerenaming/Renamers.java
  plugins/variable-renaming/src/main/java/org/vineflower/variablerenaming/TinyNameProvider.java
  plugins/variable-renaming/src/main/java/org/vineflower/variablerenaming/VariableRenamingOptions.java
  plugins/variable-renaming/src/main/java/org/vineflower/variablerenaming/VariableRenamingPlugin.java
  plugins/variable-renaming/src/main/resources/META-INF/services/org.jetbrains.java.decompiler.api.plugin.Plugin
  plugins/variable-renaming/src/test/java/org/vineflower/variablerenaming/VariableRenamingTest.java
  plugins/variable-renaming/testData/classes/custom/TestJadLvtCollision.class
  plugins/variable-renaming/testData/results/TestJadLvtCollision.dec
  plugins/variable-renaming/testData/results/pkg/TestJADNaming.dec
  plugins/variable-renaming/testData/results/pkg/TestTinyNaming.dec
  plugins/variable-renaming/testData/src/java8/pkg/TestJADNaming.java
  plugins/variable-renaming/testData/src/java8/pkg/TestTinyNaming.java
  settings.gradle
  src/org/jetbrains/java/decompiler/api/plugin/Plugin.java
  src/org/jetbrains/java/decompiler/main/ClassWriter.java
  src/org/jetbrains/java/decompiler/main/DecompilerContext.java
  src/org/jetbrains/java/decompiler/main/Fernflower.java
  src/org/jetbrains/java/decompiler/main/IdentityRenamerFactory.java
  src/org/jetbrains/java/decompiler/main/collectors/ImportCollector.java
  src/org/jetbrains/java/decompiler/main/extern/IFernflowerPreferences.java
  src/org/jetbrains/java/decompiler/main/extern/IVariableNameProvider.java
  src/org/jetbrains/java/decompiler/main/extern/IVariableNamingFactory.java
  src/org/jetbrains/java/decompiler/main/plugins/PluginContext.java
  src/org/jetbrains/java/decompiler/modules/decompiler/ExprProcessor.java
  src/org/jetbrains/java/decompiler/modules/decompiler/exps/AssignmentExprent.java
  src/org/jetbrains/java/decompiler/modules/decompiler/vars/VarDefinitionHelper.java
  src/org/jetbrains/java/decompiler/struct/ContextUnit.java
  src/org/jetbrains/java/decompiler/util/DotExporter.java
  src/org/jetbrains/java/decompiler/util/TextUtil.java
  test/org/jetbrains/java/decompiler/MinimalFernflowerEnvironment.java
  test/org/jetbrains/java/decompiler/SingleClassesTest.java
  testData/results/pkg/TestJADNaming.dec
Labels: enhancement, Priority: High, Subsystem: Variables, Subsystem: Plugins

#327 Add machine-readable annotation to describe dynamic default values
  src/org/jetbrains/java/decompiler/main/extern/IFernflowerPreferences.java
Labels: enhancement, Priority: Medium, Subsystem: User-Facing

#330 Fix @Override annotations emitting twice
  src/org/jetbrains/java/decompiler/main/ClassWriter.java
Labels: Subsystem: Writing, Priority: Medium, bugfix

#336 fix lambda to anonymous class regression
  src/org/jetbrains/java/decompiler/main/ClassWriter.java
  test/org/jetbrains/java/decompiler/SingleClassesTest.java
  testData/results/pkg/TestLambdaToAnonymousClass.dec
  testData/results/pkg/TestLambdaToAnonymousClass2.dec
  testData/src/java8/pkg/TestLambdaToAnonymousClass.java
  testData/src/java8/pkg/TestLambdaToAnonymousClass2.java
Labels: Subsystem: Writing, Priority: High, bugfix

#339 Fix a multitude of crashes and exceptions during Kotlin decompilation
  plugins/kotlin/src/main/java/org/vineflower/kotlin/KotlinChooser.java
  plugins/kotlin/src/main/java/org/vineflower/kotlin/KotlinWriter.java
  plugins/kotlin/src/main/java/org/vineflower/kotlin/expr/KConstExprent.java
  plugins/kotlin/src/main/java/org/vineflower/kotlin/expr/KFunctionExprent.java
  plugins/kotlin/src/main/java/org/vineflower/kotlin/struct/KConstructor.java
  plugins/kotlin/src/main/java/org/vineflower/kotlin/struct/KFunction.java
  plugins/kotlin/src/main/java/org/vineflower/kotlin/struct/KProperty.java
  plugins/kotlin/src/main/java/org/vineflower/kotlin/util/KTypes.java
  plugins/kotlin/testData/results/pkg/TestContracts.dec
  plugins/kotlin/testData/results/pkg/TestNonInlineLambda.dec
Labels: enhancement, Priority: Medium, Subsystem: Plugins
