Repository Vineflower/vineflower, pull requests merged in 2024-04, with the labels that each got.

#357 Fix copying of array exprents and add validation checks for duplicated exprents
  src/org/jetbrains/java/decompiler/modules/decompiler/ValidationHelper.java
  src/org/jetbrains/java/decompiler/modules/decompiler/exps/NewExprent.java
  test/org/jetbrains/java/decompiler/SingleClassesTest.java
  testData/results/pkg/TestSwitchInTry.dec
  testData/src/java8/pkg/TestSwitchInTry.java
Labels: Priority: High, Subsystem: Parsing, bugfix

#362 Fix formatter emitting blank lines for long method invocations with no arguments
  src/org/jetbrains/java/decompiler/modules/decompiler/exps/InvocationExprent.java
  test/org/jetbrains/java/decompiler/SingleClassesTest.java
  testData/results/pkg/TestBlankLinesSpaces.dec
  testData/src/java8/pkg/TestBlankLinesSpaces.java
Labels: Subsystem: Writing, Priority: Low, bugfix

#365 Only use parameter names from method parameter attributes, if they are non-null
  src/org/jetbrains/java/decompiler/main/ClassWriter.java
  testData/results/pkg/TestInnerClassesJ21.dec
Labels: Subsystem: Writing, Priority: Medium, bugfix

#366 Don't tear down nested class wrappers after writing the root class
  src/org/jetbrains/java/decompiler/main/ClassesProcessor.java
Labels: Subsystem: Writing, Priority: High, bugfix

#341 Don't write explicit casts where redundant
  plugins/kotlin/testData/results/pkg/TestTailrecFunctions.dec
  src/org/jetbrains/java/decompiler/modules/decompiler/SecondaryFunctionsHelper.java
  src/org/jetbrains/java/decompiler/modules/decompiler/exps/FunctionExprent.java
  src/org/jetbrains/java/decompiler/modules/decompiler/exps/InvocationExprent.java
  src/org/jetbrains/java/decompiler/struct/gen/TypeFamily.java
  test/org/jetbrains/java/decompiler/SingleClassesTest.java
  testData/results/pkg/TestAssignmentSwitchExpression3.dec
  testData/results/pkg/TestClassVar.dec
  testData/results/pkg/TestDebugSymbols.dec
  testData/results/pkg/TestDefiniteAssignment.dec
  testData/results/pkg/TestDoublePopAfterJump.dec
  testData/results/pkg/TestLocalsNames.dec
  testData/results/pkg/TestMethodHandles.dec
  testData/results/pkg/TestMixedCompoundAssignment.dec
  testData/results/pkg/TestMultiCast.dec
  testData/results/pkg/TestMultipleStaticBlocks.dec
  testData/results/pkg/TestNumberCasts.dec
  testData/results/pkg/TestNumberDisambiguation.dec
  testData/results/pkg/TestObjectBitwise.dec
  testData/results/pkg/TestRecordPattern3.dec
  testData/results/pkg/TestStackCastParam.dec
  testData/results/pkg/TestWhileTernary10.dec
  testData/src/java8/pkg/TestNumberCasts.java
  testData/src/java8/pkg/TestNumberDisambiguation.java
Labels: enhancement, Subsystem: Writing, Priority: Medium, unit test

#375 Fix 2 constructors of a non-static inner class with 1 calling another
  src/org/jetbrains/java/decompiler/main/rels/NestedClassProcessor.java
  test/org/jetbrains/java/decompiler/SingleClassesTest.java
  testData/results/pkg/TestInnerClasses3J21.dec
  testData/src/java21/pkg/TestInnerClasses3J21.java
Labels: Subsystem: Writing, Priority: Medium, bugfix

#379 Fix weird indent when inlined simple lambdas return something that ta…
  src/org/jetbrains/java/decompiler/main/ClassWriter.java
  testData/results/pkg/TestDoubleNestedClass.dec
Labels: Subsystem: Writing, Priority: Low, bugfix

#380 Inline empty lambda bodies to `{}` when simple lambda inlining enabled
  src/org/jetbrains/java/decompiler/main/ClassWriter.java
  test/org/jetbrains/java/decompiler/SingleClassesTest.java
  testData/results/pkg/TestEmptyLambda.dec
  testData/src/java8/pkg/TestEmptyLambda.java
Labels: Subsystem: Writing, Priority: Medium, bugfix

#376 Update Kotlin plugin to use modern Java features
  plugins/kotlin/src/main/java/org/vineflower/kotlin/KotlinWriter.java
  plugins/kotlin/src/main/java/org/vineflower/kotlin/expr/KAnnotationExprent.java
  plugins/kotlin/src/main/java/org/vineflower/kotlin/expr/KFunctionExprent.java
  plugins/kotlin/src/main/java/org/vineflower/kotlin/metadata/MetadataNameResolver.java
  plugins/kotlin/src/main/java/org/vineflower/kotlin/pass/EliminateDeadVarsPass.java
  plugins/kotlin/src/main/java/org/vineflower/kotlin/pass/KMergePass.java
  plugins/kotlin/src/main/java/org/vineflower/kotlin/pass/ReplaceExprentsPass.java
  plugins/kotlin/src/main/java/org/vineflower/kotlin/struct/DefaultArgsMap.java
  plugins/kotlin/src/main/java/org/vineflower/kotlin/struct/KConstructor.java
  plugins/kotlin/src/main/java/org/vineflower/kotlin/struct/KContract.java
  plugins/kotlin/src/main/java/org/vineflower/kotlin/struct/KFunction.java
  plugins/kotlin/src/main/java/org/vineflower/kotlin/struct/KParameter.java
  plugins/kotlin/src/main/java/org/vineflower/kotlin/struct/KProperty.java
  plugins/kotlin/src/main/java/org/vineflower/kotlin/struct/KPropertyAccessor.java
  plugins/kotlin/src/main/java/org/vineflower/kotlin/struct/KType.java
  plugins/kotlin/src/main/java/org/vineflower/kotlin/struct/KTypeParameter.java
  plugins/kotlin/src/main/java/org/vineflower/kotlin/util/KTypes.java
  plugins/kotlin/src/main/java/org/vineflower/kotlin/util/KUtils.java
  plugins/kotlin/src/main/java/org/vineflower/kotlin/util/ProtobufFlags.java
Labels: enhancement, Priority: Medium, Subsystem: Plugins

#381 Simplify empty anonymous class bodies to `{}`
  src/org/jetbrains/java/decompiler/main/ClassWriter.java
  testData/results/pkg/TestAnonymousClassConstructor.dec
  testData/results/pkg/TestAnonymousClassNaming.dec
  testData/results/pkg/TestAnonymousParamNames.dec
  testData/results/pkg/TestDoubleNestedClass.dec
Labels: Subsystem: Writing, Priority: Medium, bugfix

#382 Fix indent on 'simple' switch branches
  src/org/jetbrains/java/decompiler/modules/decompiler/exps/SwitchExprent.java
  test/org/jetbrains/java/decompiler/SingleClassesTest.java
  testData/results/pkg/TestSwitchSimpleMultiLine.dec
  testData/src/java21/pkg/TestSwitchSimpleMultiLine.java
Labels: enhancement, Subsystem: Writing, Priority: Low

#384 Fix breaking method decompilation on switch-on-enum when enum does not exist in classpath
  src/org/jetbrains/java/decompiler/modules/decompiler/SwitchHelper.java
  test/org/jetbrains/java/decompiler/SingleClassesTest.java
  testData/classes/custom/TestSwitchOnEnumWithoutEnumJ21.class
  testData/results/TestSwitchOnEnumWithoutEnumJ21.dec
Labels: Subsystem: Statement Structure, Priority: Medium, bugfix
