Repository Vineflower/vineflower, pull requests merged in 2025-02, with the labels that each got.

#451 Fix incorrect ppmm inlining
  src/org/jetbrains/java/decompiler/modules/decompiler/SimplifyExprentsHelper.java
  testData/results/pkg/TestArrayPPMM.dec
  testData/results/pkg/TestPPMM.dec
  testData/src/java8/pkg/TestArrayPPMM.java
  testData/src/java8/pkg/TestPPMM.java
Labels: Subsystem: Statement Structure, Priority: Medium, bugfix

#463 Stricter type pattern matching rules
  src/org/jetbrains/java/decompiler/modules/decompiler/SwitchPatternMatchProcessor.java
  testData/results/pkg/TestSwitchOnEnumJ21.dec
  testData/src/java21/pkg/TestSwitchOnEnumJ21.java
Labels: Subsystem: Statement Structure, Priority: High, bugfix

#464 Fix ambiguous method calls with varargs that are numbers
  src/org/jetbrains/java/decompiler/modules/decompiler/exps/InvocationExprent.java
  testData/results/pkg/TestNumberDisambiguation.dec
  testData/src/java8/pkg/TestNumberDisambiguation.java
Labels: Subsystem: Writing, Priority: High, bugfix
